// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates an enhanced report with behavioral analysis, audio transcript highlights, and suitability justifications from video interviews.
 *
 * - generateVideoInterviewAnalysisReport - A function that handles the generation of the video interview analysis report.
 * - VideoInterviewAnalysisReportInput - The input type for the generateVideoInterviewAnalysisReport function.
 * - VideoInterviewAnalysisReportOutput - The return type for the generateVideoInterviewAnalysisReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VideoInterviewAnalysisReportInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe(
      "A video of a candidate's interview, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  jobDescription: z.string().describe('The job description for the role.'),
  candidateResume: z.string().describe('The candidate resume.'),
  behavioralQuestions: z
    .array(z.string())
    .describe('The behavioral questions asked during the interview.'),
});
export type VideoInterviewAnalysisReportInput = z.infer<
  typeof VideoInterviewAnalysisReportInputSchema
>;

const VideoInterviewAnalysisReportOutputSchema = z.object({
  behavioralAnalysis: z
    .string()
    .describe('The behavioral analysis of the candidate.'),
  audioTranscriptHighlights: z
    .string()
    .describe('The highlighted sections of the audio transcript.'),
  suitabilityJustifications: z
    .string()
    .describe('The justifications for the candidate suitability.'),
});
export type VideoInterviewAnalysisReportOutput = z.infer<
  typeof VideoInterviewAnalysisReportOutputSchema
>;

export async function generateVideoInterviewAnalysisReport(
  input: VideoInterviewAnalysisReportInput
): Promise<VideoInterviewAnalysisReportOutput> {
  return videoInterviewAnalysisReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'videoInterviewAnalysisReportPrompt',
  input: {schema: VideoInterviewAnalysisReportInputSchema},
  output: {schema: VideoInterviewAnalysisReportOutputSchema},
  prompt: `You are an expert recruiter specializing in analyzing video interviews.

  You will use the video interview, job description, candidate resume, and behavioral questions to generate an enhanced report with behavioral analysis, audio transcript highlights, and suitability justifications.

  Job Description: {{{jobDescription}}}
  Candidate Resume: {{{candidateResume}}}
  Behavioral Questions: {{#each behavioralQuestions}}{{{this}}}\n{{/each}}
  Video Interview: {{media url=videoDataUri}}

  Based on the above information, generate a detailed report including:
  - Behavioral Analysis: Analyze the candidate's behavior during the interview based on their responses to the behavioral questions and overall demeanor.
  - Audio Transcript Highlights: Highlight the most relevant sections of the audio transcript that demonstrate the candidate's skills, experience, and suitability for the role.
  - Suitability Justifications: Provide justifications for the candidate's suitability for the role based on the behavioral analysis and audio transcript highlights.
  `,
});

const videoInterviewAnalysisReportFlow = ai.defineFlow(
  {
    name: 'videoInterviewAnalysisReportFlow',
    inputSchema: VideoInterviewAnalysisReportInputSchema,
    outputSchema: VideoInterviewAnalysisReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
