
"use client";

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Container } from '@/components/shared/Container';
import { generateJobDescription, GenerateJobDescriptionInput } from '@/ai/flows/job-description-generator';
import { generateTextEmbedding, GenerateTextEmbeddingInput, GenerateTextEmbeddingOutput } from '@/ai/flows/generate-text-embedding-flow'; // Import embedding flow
import { saveJobWithEmbedding } from '@/services/firestoreService'; // Import placeholder Firestore service
import { useToast } from '@/hooks/use-toast';
import { Wand2, Loader2, CheckCircle, PlusCircle, Brain } from 'lucide-react';

const jobFormSchema = z.object({
  jobTitle: z.string().min(3, { message: "Job title must be at least 3 characters." }),
  jobLevel: z.string().min(1, { message: "Please select a job level." }),
  department: z.string().min(2, { message: "Department must be at least 2 characters." }),
  location: z.string().min(2, { message: "Location must be at least 2 characters." }),
  companyName: z.string().min(2, {message: "Company name must be at least 2 characters."}), // Added company name
  responsibilities: z.string().min(20, { message: "Responsibilities must be at least 20 characters." }).describe("List key responsibilities, one per line or comma-separated."),
  qualifications: z.string().min(20, { message: "Qualifications must be at least 20 characters." }).describe("List key qualifications, one per line or comma-separated."),
});

type JobFormValues = z.infer<typeof jobFormSchema>;

export default function NewJobPage() {
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [generatedDescription, setGeneratedDescription] = useState<string | null>(null);
  const [jobEmbeddingResult, setJobEmbeddingResult] = useState<GenerateTextEmbeddingOutput | null>(null);
  const { toast } = useToast();

  const form = useForm<JobFormValues>({
    resolver: zodResolver(jobFormSchema),
    defaultValues: {
      jobTitle: '',
      jobLevel: '',
      department: '',
      location: '',
      companyName: '',
      responsibilities: '',
      qualifications: '',
    },
  });

  const handleGenerateDescription = async () => {
    const values = form.getValues();
    const validationResult = await form.trigger([
        "jobTitle", "jobLevel", "department", "location", 
        "responsibilities", "qualifications" // CompanyName not needed for JD generation
    ]); 
    if (!validationResult) {
      toast({
        variant: "destructive",
        title: "Validation Error",
        description: "Please fill in all required fields accurately before generating the description.",
      });
      return;
    }

    setIsAiLoading(true);
    setGeneratedDescription(null); 
    setJobEmbeddingResult(null); // Clear previous embedding if description is re-generated
    try {
      const input: GenerateJobDescriptionInput = {
        jobTitle: values.jobTitle,
        jobLevel: values.jobLevel,
        department: values.department,
        location: values.location,
        responsibilities: values.responsibilities,
        qualifications: values.qualifications,
      };
      const result = await generateJobDescription(input);
      setGeneratedDescription(result.jobDescription);
      toast({
        title: "Success!",
        description: "Job description generated by AI. Review and edit if needed.",
        action: <CheckCircle className="text-green-500" />,
      });
    } catch (error) {
      console.error("Error generating job description:", error);
      toast({
        variant: "destructive",
        title: "AI Generation Error",
        description: "Failed to generate job description. Please check your input or try again later.",
      });
    } finally {
      setIsAiLoading(false);
    }
  };
  
  async function onSubmit(data: JobFormValues) {
    setIsSubmitting(true);
    setJobEmbeddingResult(null);

    let jobTextForEmbedding = generatedDescription;
    if (!jobTextForEmbedding) {
        // Fallback to concatenating fields if AI description wasn't generated or used
        jobTextForEmbedding = `${data.jobTitle}\n\nCompany: ${data.companyName}\n\nLocation: ${data.location}\n\nLevel: ${data.jobLevel}\n\nDepartment: ${data.department}\n\nResponsibilities:\n${data.responsibilities}\n\nQualifications:\n${data.qualifications}`;
    }

    let currentJobEmbedding: number[] | null = null;

    try {
      // Step 1: Generate embedding for the job description text
      toast({ title: "Generating Job Embedding...", description: "AI is processing the job text."});
      const embeddingInput: GenerateTextEmbeddingInput = { text: jobTextForEmbedding };
      const embeddingOutput = await generateTextEmbedding(embeddingInput);
      currentJobEmbedding = embeddingOutput.embedding;
      setJobEmbeddingResult(embeddingOutput); // Store for display/confirmation
      toast({ title: "Job Embedding Generated", description: `Embedding created using ${embeddingOutput.modelUsed}.`, action: <Brain className="text-purple-500"/> });

      // Step 2: Simulate backend submission of job data (conceptual)
      console.log("Form submitted:", data);
      if (generatedDescription) {
        console.log("Using AI Generated description for submission:", generatedDescription);
      }
      // This is where you'd typically send `data` and `generatedDescription` (if used) to your backend to create the job record
      // and get a `jobId` back. For now, we'll simulate a jobId.
      const simulatedJobId = `job_${Date.now()}`; 
      await new Promise(resolve => setTimeout(resolve, 700)); // Simulate API call for job creation
      
      // Step 3: Save job with embedding to Firestore (placeholder call)
      if (currentJobEmbedding) {
        const firestoreJobData = {
            title: data.jobTitle,
            companyName: data.companyName, // Added company name
            fullJobDescriptionText: jobTextForEmbedding,
            jobEmbedding: currentJobEmbedding,
            location: data.location,
            jobType: data.jobLevel, // Or map jobLevel to a more specific jobType if needed
        };
        // Call the placeholder service
        const saveResult = await saveJobWithEmbedding(simulatedJobId, firestoreJobData);
        if (saveResult.success) {
            toast({ title: "Job Data & Embedding Sent to Firestore (Simulated)", description: saveResult.message });
        } else {
            throw new Error(saveResult.message); // Propagate error to be caught below
        }
      }

      toast({
        title: "Job Posted Successfully!",
        description: `The job "${data.jobTitle}" has been submitted and processed.`,
        action: <PlusCircle className="text-primary" />,
      });
      form.reset();
      setGeneratedDescription(null);
      setJobEmbeddingResult(null);

    } catch (error) {
        console.error("Error during job submission or embedding:", error);
        let errorMessage = "An unexpected error occurred.";
        if (error instanceof Error) errorMessage = error.message;
        toast({ variant: "destructive", title: "Submission Failed", description: errorMessage });
    } finally {
        setIsSubmitting(false);
    }
  }


  return (
    <Container>
      <Card className="max-w-3xl mx-auto shadow-xl">
        <CardHeader>
          <CardTitle className="text-3xl font-headline">Create New Job Posting</CardTitle>
          <CardDescription>
            Fill in the details below. You can also use our AI to help generate a compelling job description.
          </CardDescription>
        </CardHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="jobTitle"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Job Title</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Senior Software Engineer" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <FormField
                  control={form.control}
                  name="companyName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Company Name</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Tech Solutions Inc." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="jobLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Job Level</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select job level" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Entry-Level">Entry-Level</SelectItem>
                          <SelectItem value="Mid-Level">Mid-Level</SelectItem>
                          <SelectItem value="Senior-Level">Senior-Level</SelectItem>
                          <SelectItem value="Lead/Manager">Lead/Manager</SelectItem>
                          <SelectItem value="Executive">Executive</SelectItem>
                          <SelectItem value="Internship">Internship</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <FormField
                  control={form.control}
                  name="department"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Department</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Engineering, Marketing" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <FormField
                control={form.control}
                name="location"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Location</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., San Francisco, CA or Remote" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="responsibilities"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Key Responsibilities</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Enter key responsibilities, one per line or comma-separated..."
                        className="min-h-[120px]"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      Provide a clear list of the main tasks and duties for this role. AI will use this to elaborate.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="qualifications"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Qualifications & Skills</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Enter required qualifications and skills, one per line or comma-separated..."
                        className="min-h-[120px]"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      List essential skills, experience, and education needed. AI will use this to elaborate.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="space-y-2 pt-4 border-t">
                 <Label className="text-lg font-semibold">AI-Powered Job Description</Label>
                <Button type="button" variant="outline" onClick={handleGenerateDescription} disabled={isAiLoading || isSubmitting} className="w-full md:w-auto">
                  {isAiLoading ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Wand2 className="mr-2 h-4 w-4" />
                  )}
                  Generate with AI
                </Button>
                {generatedDescription && (
                  <Card className="mt-4 bg-muted/50">
                    <CardHeader>
                      <CardTitle className="text-md font-semibold">AI Generated Description Preview</CardTitle>
                       <CardDescription>Review and edit this description. If you make changes, the edited version will be used for embedding and posting.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <Textarea
                        value={generatedDescription}
                        onChange={(e) => setGeneratedDescription(e.target.value)} 
                        className="min-h-[250px] bg-background prose prose-sm max-w-none"
                        aria-label="AI Generated Job Description"
                      />
                    </CardContent>
                  </Card>
                )}
                {jobEmbeddingResult && (
                    <div className="mt-4 p-3 border rounded-md bg-green-50 text-green-700">
                        <div className="flex items-center">
                            <Brain className="mr-2 h-5 w-5"/>
                            <h4 className="font-semibold">Job Embedding Generated</h4>
                        </div>
                        <p className="text-xs mt-1">Model used: {jobEmbeddingResult.modelUsed}</p>
                        <p className="text-xs mt-1">Vector length: {jobEmbeddingResult.embedding.length}</p>
                    </div>
                )}
              </div>
            </CardContent>
            <CardFooter className="flex justify-end pt-6">
              <Button type="submit" disabled={isSubmitting || isAiLoading} size="lg">
                {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <PlusCircle className="mr-2 h-4 w-4" />}
                Post Job & Generate Embedding
              </Button>
            </CardFooter>
          </form>
        </Form>
      </Card>
    </Container>
  );
}

