
"use client";

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Container } from '@/components/shared/Container';
import { generateJobDescription } from '@/ai/flows/job-description-generator';
import { useToast } from '@/hooks/use-toast';
import { Wand2, Loader2, CheckCircle } from 'lucide-react';

const jobFormSchema = z.object({
  jobTitle: z.string().min(3, { message: "Job title must be at least 3 characters." }),
  jobLevel: z.string().min(1, { message: "Please select a job level." }),
  department: z.string().min(2, { message: "Department must be at least 2 characters." }),
  location: z.string().min(2, { message: "Location must be at least 2 characters." }),
  responsibilities: z.string().min(20, { message: "Responsibilities must be at least 20 characters." }).describe("List key responsibilities, one per line."),
  qualifications: z.string().min(20, { message: "Qualifications must be at least 20 characters." }).describe("List key qualifications, one per line."),
});

type JobFormValues = z.infer<typeof jobFormSchema>;

export default function NewJobPage() {
  const [isLoading, setIsLoading] = useState(false);
  const [generatedDescription, setGeneratedDescription] = useState<string | null>(null);
  const { toast } = useToast();

  const form = useForm<JobFormValues>({
    resolver: zodResolver(jobFormSchema),
    defaultValues: {
      jobTitle: '',
      jobLevel: '',
      department: '',
      location: '',
      responsibilities: '',
      qualifications: '',
    },
  });

  const handleGenerateDescription = async () => {
    const values = form.getValues();
    const validationResult = jobFormSchema.safeParse(values);
    if (!validationResult.success) {
      form.trigger(); // Manually trigger validation to show errors
      toast({
        variant: "destructive",
        title: "Validation Error",
        description: "Please fill in all required fields before generating the description.",
      });
      return;
    }

    setIsLoading(true);
    setGeneratedDescription(null);
    try {
      const result = await generateJobDescription(values);
      setGeneratedDescription(result.jobDescription);
      toast({
        title: "Success!",
        description: "Job description generated by AI.",
        action: <CheckCircle className="text-green-500" />,
      });
    } catch (error) {
      console.error("Error generating job description:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to generate job description. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  async function onSubmit(data: JobFormValues) {
    setIsLoading(true);
    // In a real app, you would submit this data to your backend
    console.log("Form submitted:", data);
    console.log("Generated description to save:", generatedDescription);
    
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1500));

    toast({
      title: "Job Posted!",
      description: `The job "${data.jobTitle}" has been successfully submitted.`,
      action: <CheckCircle className="text-green-500" />,
    });
    form.reset();
    setGeneratedDescription(null);
    setIsLoading(false);
  }


  return (
    <Container>
      <Card className="max-w-3xl mx-auto shadow-xl">
        <CardHeader>
          <CardTitle className="text-3xl font-headline">Create New Job Posting</CardTitle>
          <CardDescription>
            Fill in the details below. You can also use our AI to help generate a compelling job description.
          </CardDescription>
        </CardHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="jobTitle"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Job Title</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Senior Software Engineer" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="jobLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Job Level</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select job level" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Entry-Level">Entry-Level</SelectItem>
                          <SelectItem value="Mid-Level">Mid-Level</SelectItem>
                          <SelectItem value="Senior-Level">Senior-Level</SelectItem>
                          <SelectItem value="Lead/Manager">Lead/Manager</SelectItem>
                          <SelectItem value="Executive">Executive</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="department"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Department</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Engineering, Marketing" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="location"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Location</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., San Francisco, CA or Remote" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="responsibilities"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Key Responsibilities</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Enter key responsibilities, one per line..."
                        className="min-h-[120px]"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      Clearly list the main tasks and duties for this role.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="qualifications"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Qualifications & Skills</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Enter required qualifications and skills, one per line..."
                        className="min-h-[120px]"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      List essential skills, experience, and education needed.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="space-y-2">
                <Button type="button" variant="outline" onClick={handleGenerateDescription} disabled={isLoading} className="w-full md:w-auto">
                  {isLoading && generatedDescription === null ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Wand2 className="mr-2 h-4 w-4" />
                  )}
                  Generate Job Description with AI
                </Button>
                {generatedDescription && (
                  <Card className="mt-4 bg-muted/50">
                    <CardHeader>
                      <CardTitle className="text-lg font-semibold">AI Generated Description Preview</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <Textarea
                        value={generatedDescription}
                        readOnly
                        className="min-h-[200px] bg-background"
                      />
                      <p className="text-xs text-muted-foreground mt-2">
                        You can copy this description or use it as inspiration. Make sure to review and edit as needed.
                      </p>
                    </CardContent>
                  </Card>
                )}
              </div>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button type="submit" disabled={isLoading} size="lg">
                {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                Post Job
              </Button>
            </CardFooter>
          </form>
        </Form>
      </Card>
    </Container>
  );
}
